### PR TITLE
Removed hidden quests from quest log

### PR DESCRIPTION
**Pull request by SteveEbey73742**
Figured out that 140 was quest type for arena and bg quests, and was able to have the carbonite log display skip them.

### CODE REVIEW

**Comment by IrcDirk** [comment]
U mean those weekly quests for PVP? But there might by other PVP quests which might be skiped becouse they have type 140! 

Im not sure if this is good solution.

**Comment by SteveEbey73742** [comment]
I think 140 means hidden, not pvp, but I can see if other pvp quest show up.  Otherwise I would say it is working, as I have had no issues running it.  Anyone here do pvp to test it? I am on a pve realm.

**Comment by IrcDirk** [comment]
I got alt on PVP realm... but need to find other some PVP quests to test it ;)

**Comment by SteveEbey73742** [comment]
tried going to ashran in stormshield, but all my alts have finished those quests.

**Comment by SteveEbey73742** [comment]
closing this one, found the doc in the api git that had the full questlogtitle returns and isHidden is returned so I made a mod to my fork, and will be testing it this evening.  If it works, I will make a fresh pull request.

**Pull request closed without merging**
