### PR TITLE
Watch Window cleanup and Quest Log fix

### PR DESCRIPTION
**Pull request by SteveEbey73742**
Removed the not in database from the watch window, and also fixed the log so that show objective doesn't fill the screen with nil or ?.  If a person clicks on an objective on the log, that is not in the database, the code fix catches it, and does not error out.

### CODE REVIEW

**Comment by IrcDirk** [comment]
Ill dont know if thats a good idea... Since there are quests that are not in database at all, they are resolved by alternative method. Objectives are based on quest info and POIs on map. If they have no POIs they will be "not in databse" but they are on the list. They should not be hidden... Or am i wrong?

**Comment by IrcDirk** [comment]
Good example are quests for Legion proffesions those u need to gather something.

**Comment by SteveEbey73742** [comment]
Quest are still on watch list, just hid the not found in database objectives, to remove some clutter.  Not hiding the actual quest.

**Comment by IrcDirk** [comment]
Hidding not found objectives is a bad idea since they are there and should be there, but are not found becouse POIs are not visible on map. We should keep them since they are important to know what to do ;)

**Comment by SteveEbey73742** [comment]
They are on the main log, just not the watch window. I can add a trap to use the blizz functions to get them, so that they do show on the watch window, but then people might try and track them, and since the poi is not known, not sure if that is a good idea.

**Comment by IrcDirk** [comment]
sorry but had to revert it:

1. before

![after]http://i.imgur.com/I5ignWg.png

2. after your changes

![after]http://i.imgur.com/cZwpTQ6.png

**Pull request merged**
