### PR TITLE
herbalism and mining shadowland support

### PR DESCRIPTION
**Pull request by qlesz**
as in title
[Carbonite.lua.txt](https://github.com/mikepauer/Carbonite/files/5667099/Carbonite.lua.txt)
[NxOptions.lua.txt](https://github.com/mikepauer/Carbonite/files/5667102/NxOptions.lua.txt)

### CODE REVIEW

**Comment by IrcDirk** [comment]
Why did u pushed so much commits with this pull request? It should be changes in only 2 files ;)

**Comment by Thrumbar** [comment]
Me thinks he should of updated before he made changed and pushed.  Almost pooped myself..

**Comment by IrcDirk** [comment]
Yep, he should update his FORK before applying changes. I can aprove this pull...

**Comment by qlesz** [comment]
i am sorry this was my first time and i have not really knew how to do it so i could mess something up

**Comment by IrcDirk** [comment]
No problem. U need to make fork and make sure its always uptodate. Then make changes and create pull.

Closing.

**Pull request closed without merging**
