### PR TITLE
WorldMapTooltip changed to GameTooltip

### PR DESCRIPTION
**Pull request by Thrumbar**

### CODE REVIEW

**Comment by IrcDirk** [comment]
Thats for 8.1.5?

**Comment by Thrumbar** [comment]
Yes made changes based on live server but did not mean to push the ace with it

**Comment by IrcDirk** [comment]
Which ace is it 1199? There is 1200 Release.

**Comment by Thrumbar** [comment]
Tried to push the tooltip changed to here and the ace to my fork but they both wound up here.  Off to work be back in 9 hours..

**Pull request closed without merging**
