### PR TITLE
Code Cleanup, nothing changed

### PR DESCRIPTION
**Pull request by SteveEbey73742**
My goal is to speed up file load and compile time, by eliminating the commented out debug code.  I left all the code blocks intact that were commented out, for the original person who commented them, to deal with. I would not presume to remove code just because it is commented out, unless I knew for sure it was no longer viable.

### CODE REVIEW

**Comment by mikepauer** [comment]
Anything commented out, can be removed.. Some are rewritten functions that the original was left as notes, others are defunc or old code, some is stuff the original cbc team had written and commented out themselves and I left it alone.

**Comment by IrcDirk** [comment]
I dont like this, becouse i sometime benefit from those lines... learned a lot by testing what they do. A to compilation they are comments so they should not affect compilation time since they are ignored.

**Comment by SteveEbey73742** [comment]
Clarification, i removed the nxprt that were clearly debug prints, when modules were being tested, not comments on the ends of lines, or blocks of commented code.  Those remain.

**Comment by IrcDirk** [comment]
Ok ill check it.

**Comment by IrcDirk** [comment]
Im closing this pull, please remove only debug/commented Nx.prt, others leave. Sorry :)

**Pull request closed without merging**
