### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by fdellwing**
first look at the github readme, took the curse description and modified it in parts. Should be reworked completely, to be more actual and acurate

will look into getting an api for pulling the download count from curse in the next days

### CODE REVIEW

**Comment by fdellwing** [comment]
So, I finished the first step of the API. Its slow as fuck, but it works. Will integrate a caching methode to speed things up and stop spamming curse.

It works like this:

You have an image url like this: http://zerosgaming.de/curse_api/carbonite-monthly.svg

The two codewords are carbonite and monthly, they server does a rewrite of this .svg to a php file, that gets the paramters from the filename of the image. This php script than pulls an JSON from another php file that contains the downloads (this will be cached) and simply outputs a readfile() of https://shields.io/.

So effective the badges are comming from shields.io but I'm doing the inserting of the current numbers :)

**Comment by fdellwing** [comment]
Implemented caching and pushed the project to github so you can have a look :)

https://github.com/fdellwing/curse_api

**Comment by fdellwing** [comment]
We could be also using codeclimate.com, but @mikepauer would need to setup this beforehand. It's quite easy, as you can use githubs oAuth.

This is the badge from my fork: [Test Coverage](https://codeclimate.com/github/fdellwing/Carbonite-1/issues)

**Comment by fdellwing** [comment]
@IrcDirk @mikepauer Any thoughts on that? It is not really needed for Curse or WoW-Interface, but it would look a lot cleaner on github.

**Comment by IrcDirk** [comment]
It looks good but i dont know if we need this, as we have autopackage to curse and wowi and people, should download from there not from github ;) But if we set autopackege to ignore this file and not include it with curse and wowi im not agaist it.

**Pull request closed without merging**
