### PR TITLE
SetCustomWaypoint parameters chaged to emulate current TomTom version

### PR DESCRIPTION
**Pull request by Kaboca**
Tested with Routes addon

### CODE REVIEW

**Comment by IrcDirk** [comment]
This can break functionality with addons that did not updated to new TomTom waypoints. Can u make version that supports both at the same time?

**Comment by IrcDirk** [comment]
This can break functionality with addons that did not updated to new TomTom waypoints. Can u make version that supports both at the same time?

**Comment by Kaboca** [comment]
This is a TomTom interface change, which is already done. Carbonite TomTom emulation only follow those changes.
Therefore, I don't know how to support two versions of the TomTom interface.
The internal functions of Carbonite have not changed.

If an application depends on TomTom interface, it will no longer work with TomTom.
Why keep Carbonite in an old state for the sake of addons that don’t keep up with the changes.

**Comment by Kaboca** [comment]
Side note: This is a one year old TomTom interface change :) - but thanks for the merge!

**Comment by IrcDirk** [comment]
No problem ;) Thanks for making this pull request

**Pull request merged**
